version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/python:3.10.1 # CircleCI convenience image with common Python tools
    steps:
      - checkout # checks out the code from your repo.
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace: # saves the output of your test
          root: ~/project
          paths: . 
