version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build: 
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Testing
          command: python -m pytest
  deploy: 
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Hello World
          command: |
            # echo 'Hello World'
            python --version
            python hello-world.py