version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build-test: # this can be any name you choose
    docker:
      - image: cimg/python:3.10.1 # CircleCI convenience image with common Python tools
    steps:
      - checkout # checks out the code from your repo.
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Testing
          command: python -m pytest
  deploy: 
    docker:
      - image: cimg/python:3.10.1
    steps:
      - run:
          name: Hello World
          command: |
            # echo 'Hello World'
            python --version
            python hello-world
workflows:
  Python-Workflow:
    jobs:
      - build-test
      - deploy:
          requires:
            - build-test
